version: '3.7'

services:
  php:
    image: trafex/php-nginx
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:8080
      
# services:
#   php-env:
#     # build: .
#     image: harbor.strikerlulu.me/cubet/laravel_apache:latest
#     volumes:
#       - ./:/var/www/html/src/public
#     ports:
#       - 9000:80

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_managment_app
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data: