apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: shamil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          # lifecycle:
          #   postStart:
          #     exec:
          #       command: ["/bin/sh", "-c", "sleep 30 && curl https://strikerlulu.me/shamil.sql > shamil.sql && mysql mobile_store -proot < shamil.sql "]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: mobile_store
            - name: MYSQL_USER
              value: shamil
            - name: MYSQL_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: task-managment-app-db-volume
              mountPath: /var/lib/mysql # Replace with the path where you want to mount the PV inside the container
      volumes:
        - name: task-managment-app-db-volume
          persistentVolumeClaim:
            claimName: task-managment-app-db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: shamil
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: task-managment-app-service
  namespace: shamil
spec:
  selector:
    app: task-managment-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-managment-app
  namespace: shamil
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/custom-http-errors: "418"
spec:
  ingressClassName: nginx
  rules:
    - host: task-managment-app.k.strikerlulu.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: task-managment-app-service
                port:
                  number: 8080
  tls:
    - hosts:
      - task-managment-app.k.strikerlulu.me
      secretName: task-managment-app-ingress-cert
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-managment-app-uploads
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: shamil
    name: task-managment-app-uploads
  hostPath:
    path: /data/task-managment-app/uploads # Replace with the actual host path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-managment-app-uploads
  namespace: shamil
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the storage size as needed
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-managment-app-db
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: shamil
    name: task-managment-app-db
  hostPath:
    path: /data/task-managment-app/db # Replace with the actual host path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-managment-app-db
  namespace: shamil
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the storage size as needed

