// service-worker.js

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';

// Precache all assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);

// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy.
registerRoute(
  /^https:\/\/fonts\.googleapis\.com/,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// Cache the Google Fonts webfont files with a cache-first strategy for 1 year.
registerRoute(
  /^https:\/\/fonts\.gstatic\.com/,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheFirst.CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache images with a cache-first strategy.
registerRoute(
  /\.(?:png|gif|jpg|jpeg|webp|svg)$/,
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new CacheFirst.CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Handle navigation requests for React Router apps.
// This assumes that your build output is in the 'build' directory.
// Adjust this to match your build configuration.
registerRoute(
  // Add your own condition here to match navigation requests.
  ({ request }) => request.mode === 'navigate',
  async ({ url }) => {
    try {
      // Use a CacheFirst strategy to serve the navigation route,
      // in case there's an update available from the network.
      return await caches.match('build/index.html');
    } catch (error) {
      console.error('Error in service worker navigation route:', error);
      throw error;
    }
  }
);
