name: Build and Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate tag
        id: generate_tag
        run: echo "::set-output name=TAG::$(git rev-parse --short HEAD)"

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: harbor.strikerlulu.me
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push Docker image
      #   run: |
      #     docker build -f Dockerfile.k8s -t harbor.strikerlulu.me/coding-strikerz/task-managment-app:${{ steps.generate_tag.outputs.TAG }} .
      #     docker push harbor.strikerlulu.me/coding-strikerz/task-managment-app:${{ steps.generate_tag.outputs.TAG }}

      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          token: ${{ secrets.DEPOT_TOKEN }}
          project: ll2tdnqtgh
          push: true
          file: Dockerfile.k8s
          tags: harbor.strikerlulu.me/coding-strikerz/task-managment-app:${{ steps.generate_tag.outputs.TAG }}
          platforms: linux/arm64

      # - name: Configure Kubernetes cluster
      #   run: |
      #     echo "$KUBECONFIG" | base64 --decode > kubeconfig.yaml

      - name: Update image tag in deployment.yml
        run: |
          sed -i "s|image: harbor.strikerlulu.me/coding-strikerz/task-managment-app:.*|image: harbor.strikerlulu.me/coding-strikerz/task-managment-app:${{ steps.generate_tag.outputs.TAG }}|" deployment.yml

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Change context
        run: |
          kubectl config use-context oracle

      - name: Deploy to Kubernetesa
        run: |
          kubectl apply -f deployment.yml

