name: Build and Deploy

on:
  push:
    branches: [master , main]

  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Other steps can refer to files in the 'react' directory
      - name: Set up Depot CLI
        run: |
          cd react
          # Your set up commands here
          cd ..

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: harbor.strikerlulu.me
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          token: ${{ secrets.DEPOT_TOKEN }}
          project: ll2tdnqtgh
          push: true
          file: react/Dockerfile.k8s
          tags: harbor.strikerlulu.me/coding-strikerz/task-managment-app:${{ steps.generate_tag.outputs.TAG }}
          platforms: linux/arm64

      - name: Update image tag in deployment.yml
        run: |
          sed -i "s|image: harbor.strikerlulu.me/coding-strikerz/task-managment-app:.*|image: harbor.strikerlulu.me/coding-strikerz/task-managment-app:${{ steps.generate_tag.outputs.TAG }}|" react/deployment.yml

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Change context
        run: |
          kubectl config use-context oracle

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f react/deployment.yml
